#!/bin/sh

# xinitrc runs automatically when you run startx.

# There are some small but important commands that need to be run when we start
# the graphical environment. I keep those commands in ~/.xprofile because
# that file is run automatically if someone uses a display manager (login
# screen) and so they are needed there. To prevent doubling up commands, I
# source them here with the line below.

Sets DBus environment variables on non-systemd distros.
if [ -z "$DBUS_SESSION_BUS_ADDRESS" ]; then
	eval `dbus-launch --exit-with-session --sh-syntax`
fi

systemctl --user import-environment DISPLAY XAUTHORITY 

if command -v dbus-update-activation-environment >/dev/null 2>&1; then
	dbus-update-activation-environment DISPLAY XAUTHORITY
fi


# GnuPG agent stuff yeah yeah
if [ -x /usr/bin/gpg-agent ]; then
	eval "$(/usr/bin/gpg-agent --daemon)"
fi

if [ -f "$HOME/x11/xprofile" ]; then
	. "$HOME/.xprofile"
fi

ssh-agent leftwm
