#!/bin/sh

filename="$(date "+%s").png"
savedir="${XDG_PICTURES_DIR:-"$HOME/pictures"}/00screenshots/$(date "+%m-%Y")"

[ -d "$savedir" ] || mkdir -p "$savedir"

hyprshot -m output -f "$filename" -o "$savedir"
