#!/bin/bash

for id in $(loginctl list-sessions -j | jq -r '.[] | .session') ; do 
	if [[ $(loginctl show-session $id --property=Type) =~ (wayland|x11) ]] ; then
		systemd-run --machine=$(loginctl show-session $id --property=Name --value)@.host --user \
			notify-send -a 'System' -u critical -i battery 'Low battery (20%)' 'Please charge your device'
	fi
done
